version: '3'

services:
    prometheus:
      image: prom/prometheus
      command: --config.file=/etc/prom.yml
      volumes:
        - /etc/prom.yml:/etc/prom.yml
      ports: 
        - "9090"
    grafana:
      image: grafana/grafana
      volumes: 
        - /opt/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      ports:
        - "3000"
      environment:
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_BASIC_ENABLED: "false"
        GF_SERVER_ROOT_URL: "http://grafana"
    proxy:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - /etc/nginx.conf:/etc/nginx/nginx.conf
        - /etc/passwords:/etc/nginx/passwords
